//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: AlternatingMutlicMoveAlgo.java
//
//  Created by amahfouz on 6/4/14.
//

#include "Move.h"
#include "MulticMoveAlgo.h"
#include "MutableGameState.h"
#include "java/lang/IllegalArgumentException.h"

#import "AlternatingMutlicMoveAlgo.h"

@implementation MMCAlternatingMutlicMoveAlgo

- (id)initWithMMCMulticMoveAlgo:(id<MMCMulticMoveAlgo>)firstAlgo
          withMMCMulticMoveAlgo:(id<MMCMulticMoveAlgo>)secondAlgo
                        withInt:(int)numTimesToRunFirstAlgoBeforeAlternating {
  if (self = [super init]) {
    if (firstAlgo == nil || secondAlgo == nil) @throw [[JavaLangIllegalArgumentException alloc] init];
    self->firstAlgo_ = firstAlgo;
    self->secondAlgo_ = secondAlgo;
    self->numTimesToRunFirstAlgoBeforeAlternating_ = numTimesToRunFirstAlgoBeforeAlternating;
    self->remainingCounter_ = numTimesToRunFirstAlgoBeforeAlternating;
  }
  return self;
}

- (id<MMCMove>)findNextMoveWithMMCMutableGameState:(MMCMutableGameState *)curGameState {
  if (remainingCounter_ == 0) {
    remainingCounter_ = numTimesToRunFirstAlgoBeforeAlternating_;
    return [((id<MMCMulticMoveAlgo>) nil_chk(secondAlgo_)) findNextMoveWithMMCMutableGameState:curGameState];
  }
  --remainingCounter_;
  return [((id<MMCMulticMoveAlgo>) nil_chk(firstAlgo_)) findNextMoveWithMMCMutableGameState:curGameState];
}

- (void)copyAllFieldsTo:(MMCAlternatingMutlicMoveAlgo *)other {
  [super copyAllFieldsTo:other];
  other->firstAlgo_ = firstAlgo_;
  other->numTimesToRunFirstAlgoBeforeAlternating_ = numTimesToRunFirstAlgoBeforeAlternating_;
  other->remainingCounter_ = remainingCounter_;
  other->secondAlgo_ = secondAlgo_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "initWithMMCMulticMoveAlgo:withMMCMulticMoveAlgo:withInt:", "AlternatingMutlicMoveAlgo", NULL, 0x1, NULL },
    { "findNextMoveWithMMCMutableGameState:", "findNextMove", "Lcom.mahfouz.multic.core.Move;", 0x1, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "firstAlgo_", NULL, 0x12, "Lcom.mahfouz.multic.core.MulticMoveAlgo;", NULL,  },
    { "secondAlgo_", NULL, 0x12, "Lcom.mahfouz.multic.core.MulticMoveAlgo;", NULL,  },
    { "numTimesToRunFirstAlgoBeforeAlternating_", NULL, 0x12, "I", NULL,  },
    { "remainingCounter_", NULL, 0x2, "I", NULL,  },
  };
  static J2ObjcClassInfo _MMCAlternatingMutlicMoveAlgo = { "AlternatingMutlicMoveAlgo", "com.mahfouz.multic.core", NULL, 0x11, 2, methods, 4, fields, 0, NULL};
  return &_MMCAlternatingMutlicMoveAlgo;
}

@end
