//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: BoardDef.java
//
//  Created by amahfouz on 6/4/14.
//

#ifndef _MMC_BoardDef_H_
#define _MMC_BoardDef_H_

@class IOSIntArray;
@class IOSObjectArray;

#import "JreEmulation.h"

#define MMCBoardDef_GRID_DIM 6
#define MMCBoardDef_NUM_CELLS 36


/**
 @brief Definition of board cells and all combinations of fours in a row.
 */
@interface MMCBoardDef : NSObject {
}

+ (int)getIndexForProductWithInt:(int)product;

/**
 @brief Return all fours in which the cell with the specified product participates.
 */

+ (IOSIntArray *)getFourIndicesForWithInt:(int)product;

+ (IOSIntArray *)getFactorsForProductAtIndexWithInt:(int)productIndex;

- (id)init;

@end

FOUNDATION_EXPORT BOOL MMCBoardDef_initialized;
J2OBJC_STATIC_INIT(MMCBoardDef)

J2OBJC_STATIC_FIELD_GETTER(MMCBoardDef, GRID_DIM, int)

J2OBJC_STATIC_FIELD_GETTER(MMCBoardDef, NUM_CELLS, int)

FOUNDATION_EXPORT IOSIntArray *MMCBoardDef_PRODUCTS_;
J2OBJC_STATIC_FIELD_GETTER(MMCBoardDef, PRODUCTS_, IOSIntArray *)

FOUNDATION_EXPORT IOSObjectArray *MMCBoardDef_FOURS_;
J2OBJC_STATIC_FIELD_GETTER(MMCBoardDef, FOURS_, IOSObjectArray *)

FOUNDATION_EXPORT IOSIntArray *MMCBoardDef_INDEX_FOR_PRODUCT_;
J2OBJC_STATIC_FIELD_GETTER(MMCBoardDef, INDEX_FOR_PRODUCT_, IOSIntArray *)

FOUNDATION_EXPORT IOSObjectArray *MMCBoardDef_FOUR_INDICES_FOR_PRODUCT_;
J2OBJC_STATIC_FIELD_GETTER(MMCBoardDef, FOUR_INDICES_FOR_PRODUCT_, IOSObjectArray *)

FOUNDATION_EXPORT IOSObjectArray *MMCBoardDef_FACTORS_FOR_PRODUCT_;
J2OBJC_STATIC_FIELD_GETTER(MMCBoardDef, FACTORS_FOR_PRODUCT_, IOSObjectArray *)

typedef MMCBoardDef ComMahfouzMulticCoreBoardDef;

#endif // _MMC_BoardDef_H_
