//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Difficulty.java
//
//  Created by amahfouz on 6/4/14.
//

#ifndef MMC_Difficulty_H_

#define MMC_Difficulty_H_

#import "JreEmulation.h"
#include "java/lang/Enum.h"

typedef enum {
  MMCDifficulty_SILLY = 0,
  MMCDifficulty_EASY = 1,
  MMCDifficulty_MEDIUM = 2,
  MMCDifficulty_HARD = 3,
  MMCDifficulty_EXPERT = 4,
} MMCDifficulty;

@interface MMCDifficultyEnum : JavaLangEnum < NSCopying > {
}
+ (IOSObjectArray *)values;
+ (MMCDifficultyEnum *)valueOfWithNSString:(NSString *)name;
- (id)copyWithZone:(NSZone *)zone;

- (id)initWithNSString:(NSString *)__name withInt:(int)__ordinal;
@end

FOUNDATION_EXPORT BOOL MMCDifficultyEnum_initialized;
J2OBJC_STATIC_INIT(MMCDifficultyEnum)

FOUNDATION_EXPORT MMCDifficultyEnum *MMCDifficultyEnum_values[];

#define MMCDifficultyEnum_SILLY MMCDifficultyEnum_values[MMCDifficulty_SILLY]
J2OBJC_STATIC_FIELD_GETTER(MMCDifficultyEnum, SILLY, MMCDifficultyEnum *)

#define MMCDifficultyEnum_EASY MMCDifficultyEnum_values[MMCDifficulty_EASY]
J2OBJC_STATIC_FIELD_GETTER(MMCDifficultyEnum, EASY, MMCDifficultyEnum *)

#define MMCDifficultyEnum_MEDIUM MMCDifficultyEnum_values[MMCDifficulty_MEDIUM]
J2OBJC_STATIC_FIELD_GETTER(MMCDifficultyEnum, MEDIUM, MMCDifficultyEnum *)

#define MMCDifficultyEnum_HARD MMCDifficultyEnum_values[MMCDifficulty_HARD]
J2OBJC_STATIC_FIELD_GETTER(MMCDifficultyEnum, HARD, MMCDifficultyEnum *)

#define MMCDifficultyEnum_EXPERT MMCDifficultyEnum_values[MMCDifficulty_EXPERT]
J2OBJC_STATIC_FIELD_GETTER(MMCDifficultyEnum, EXPERT, MMCDifficultyEnum *)

#endif // MMC_Difficulty_H_
