//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Knob.java
//
//  Created by amahfouz on 6/4/14.
//

#ifndef _MMC_Knob_H_

#define _MMC_Knob_H_

#import "JreEmulation.h"
#include "java/lang/Enum.h"

#define MMCKnob_MAX_FACTOR 9
#define MMCKnob_MIN_FACTOR 1


/**
 @brief State of a knob
 */
@interface MMCKnob : NSObject {
}

+ (BOOL)isValidPosWithInt:(int)pos;

- (id)init;

@end

__attribute__((always_inline)) inline void MMCKnob_init() {}

J2OBJC_STATIC_FIELD_GETTER(MMCKnob, MIN_FACTOR, int)

J2OBJC_STATIC_FIELD_GETTER(MMCKnob, MAX_FACTOR, int)

typedef MMCKnob ComMahfouzMulticCoreKnob;

typedef enum {
  MMCKnob_Location_TOP = 0,
  MMCKnob_Location_BOTTOM = 1,
} MMCKnob_Location;

@interface MMCKnob_LocationEnum : JavaLangEnum < NSCopying > {
 @public
  NSString *label_;
}
+ (IOSObjectArray *)values;
+ (MMCKnob_LocationEnum *)valueOfWithNSString:(NSString *)name;
- (id)copyWithZone:(NSZone *)zone;

- (id)initWithNSString:(NSString *)label
          withNSString:(NSString *)__name
               withInt:(int)__ordinal;

- (NSString *)getLabel;
@end

FOUNDATION_EXPORT BOOL MMCKnob_LocationEnum_initialized;
J2OBJC_STATIC_INIT(MMCKnob_LocationEnum)

FOUNDATION_EXPORT MMCKnob_LocationEnum *MMCKnob_LocationEnum_values[];

#define MMCKnob_LocationEnum_TOP MMCKnob_LocationEnum_values[MMCKnob_Location_TOP]
J2OBJC_STATIC_FIELD_GETTER(MMCKnob_LocationEnum, TOP, MMCKnob_LocationEnum *)

#define MMCKnob_LocationEnum_BOTTOM MMCKnob_LocationEnum_values[MMCKnob_Location_BOTTOM]
J2OBJC_STATIC_FIELD_GETTER(MMCKnob_LocationEnum, BOTTOM, MMCKnob_LocationEnum *)

J2OBJC_FIELD_SETTER(MMCKnob_LocationEnum, label_, NSString *)

@interface MMCKnob_Pos : NSObject {
 @public
  int pos_;
}

- (id)initWithInt:(int)pos;

- (int)get;

- (void)setWithInt:(int)newPos;

- (void)copyAllFieldsTo:(MMCKnob_Pos *)other;

@end

__attribute__((always_inline)) inline void MMCKnob_Pos_init() {}

#endif // _MMC_Knob_H_
