//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: MinimaxMulticMoveAlgo.java
//
//  Created by amahfouz on 6/4/14.
//

#ifndef _MMC_MinimaxMulticMoveAlgo_H_
#define _MMC_MinimaxMulticMoveAlgo_H_

@class MMCMove_Immutable;
@class MMCMutableGameState;
@protocol MMCMove;
@protocol MMUMulticLog;

#import "JreEmulation.h"
#include "MulticMoveAlgo.h"

#define MMCMinimaxMulticMoveAlgo_MAX_MAX_DEPTH 5


/**
 @brief Minimax algorithm for choosing the next move.
 */
@interface MMCMinimaxMulticMoveAlgo : NSObject < MMCMulticMoveAlgo > {
 @public
  int maxDepth_;
  id<MMUMulticLog> log_;
  MMCMutableGameState *gameState_;
  MMCMove_Immutable *moveToMake_;
}

- (id)initWithInt:(int)maxDepth
 withMMUMulticLog:(id<MMUMulticLog>)log;

- (id<MMCMove>)findNextMoveWithMMCMutableGameState:(MMCMutableGameState *)gameState;

- (int)evalNodeWithInt:(int)remainingDepth
           withBoolean:(BOOL)isMaximizing;

- (int)addDepthToValueWithInt:(int)nodeValue
                      withInt:(int)remainingDepth;

- (void)copyAllFieldsTo:(MMCMinimaxMulticMoveAlgo *)other;

@end

__attribute__((always_inline)) inline void MMCMinimaxMulticMoveAlgo_init() {}

J2OBJC_FIELD_SETTER(MMCMinimaxMulticMoveAlgo, log_, id<MMUMulticLog>)
J2OBJC_FIELD_SETTER(MMCMinimaxMulticMoveAlgo, gameState_, MMCMutableGameState *)
J2OBJC_FIELD_SETTER(MMCMinimaxMulticMoveAlgo, moveToMake_, MMCMove_Immutable *)

J2OBJC_STATIC_FIELD_GETTER(MMCMinimaxMulticMoveAlgo, MAX_MAX_DEPTH, int)

typedef MMCMinimaxMulticMoveAlgo ComMahfouzMulticCoreMinimaxMulticMoveAlgo;

#endif // _MMC_MinimaxMulticMoveAlgo_H_
