//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: MoveIterator.java
//
//  Created by amahfouz on 6/4/14.
//

#ifndef _MMC_MoveIterator_H_
#define _MMC_MoveIterator_H_

@class MMCKnob_LocationEnum;
@class MMCMove_Mutable;
@class MMCMutableGameState;

#import "JreEmulation.h"


/**
 @brief Enumerates valid moves given knob states and cell states.
 */
@interface MMCMoveIterator : NSObject {
 @public
  MMCMutableGameState *game_;
  MMCKnob_LocationEnum *curKnob_;
  int curPos_;
}

- (id)initWithMMCMutableGameState:(MMCMutableGameState *)gameState;

- (BOOL)hasNext;

- (void)getNextWithMMCMove_Mutable:(MMCMove_Mutable *)mutableMove;

- (void)findNextValidMove;

- (void)copyAllFieldsTo:(MMCMoveIterator *)other;

@end

__attribute__((always_inline)) inline void MMCMoveIterator_init() {}

J2OBJC_FIELD_SETTER(MMCMoveIterator, game_, MMCMutableGameState *)
J2OBJC_FIELD_SETTER(MMCMoveIterator, curKnob_, MMCKnob_LocationEnum *)

typedef MMCMoveIterator ComMahfouzMulticCoreMoveIterator;

#endif // _MMC_MoveIterator_H_
