//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: MoveIterator.java
//
//  Created by amahfouz on 6/4/14.
//

#include "Knob.h"
#include "Knobs.h"
#include "Move.h"
#include "MutableGameState.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/IllegalStateException.h"

#import "MoveIterator.h"

@implementation MMCMoveIterator

- (id)initWithMMCMutableGameState:(MMCMutableGameState *)gameState {
  if (self = [super init]) {
    if (gameState == nil) @throw [[JavaLangIllegalArgumentException alloc] init];
    self->game_ = gameState;
    self->curKnob_ = MMCKnob_LocationEnum_get_TOP();
    [self findNextValidMove];
  }
  return self;
}

- (BOOL)hasNext {
  return curKnob_ != nil;
}

- (void)getNextWithMMCMove_Mutable:(MMCMove_Mutable *)mutableMove {
  if (![self hasNext]) @throw [[JavaLangIllegalStateException alloc] initWithNSString:@"No more moves."];
  [((MMCMove_Mutable *) nil_chk(mutableMove)) setWithMMCKnob_LocationEnum:curKnob_ withInt:curPos_];
  [self findNextValidMove];
}

- (void)findNextValidMove {
  while (YES) {
    curPos_++;
    if (![MMCKnob isValidPosWithInt:curPos_]) {
      if (curKnob_ == MMCKnob_LocationEnum_get_TOP() && ![((MMCKnobs *) nil_chk([((MMCMutableGameState *) nil_chk(game_)) getKnobs])) areAtSamePos]) {
        curKnob_ = MMCKnob_LocationEnum_get_BOTTOM();
        curPos_ = 0;
        continue;
      }
      else {
        curKnob_ = nil;
        break;
      }
    }
    if (curPos_ != [((MMCKnobs *) nil_chk([((MMCMutableGameState *) nil_chk(game_)) getKnobs])) getPosForWithMMCKnob_LocationEnum:curKnob_] && ([game_ isValidMoveWithMMCKnob_LocationEnum:curKnob_ withInt:curPos_])) break;
  }
}

- (void)copyAllFieldsTo:(MMCMoveIterator *)other {
  [super copyAllFieldsTo:other];
  other->curKnob_ = curKnob_;
  other->curPos_ = curPos_;
  other->game_ = game_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "initWithMMCMutableGameState:", "MoveIterator", NULL, 0x1, NULL },
    { "hasNext", NULL, "Z", 0x1, NULL },
    { "getNextWithMMCMove_Mutable:", "getNext", "V", 0x1, NULL },
    { "findNextValidMove", NULL, "V", 0x2, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "game_", NULL, 0x12, "Lcom.mahfouz.multic.core.MutableGameState;", NULL,  },
    { "curKnob_", NULL, 0x2, "Lcom.mahfouz.multic.core.Knob$Location;", NULL,  },
    { "curPos_", NULL, 0x2, "I", NULL,  },
  };
  static J2ObjcClassInfo _MMCMoveIterator = { "MoveIterator", "com.mahfouz.multic.core", NULL, 0x11, 4, methods, 3, fields, 0, NULL};
  return &_MMCMoveIterator;
}

@end
