//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Move.java
//
//  Created by amahfouz on 6/4/14.
//

#ifndef MMCMove_H
#define MMCMove_H

@class MMCKnob_LocationEnum;

#import "JreEmulation.h"


/**
 @brief Specifies a move made either by human or computer.
 */
@protocol MMCMove < NSObject, JavaObject >

- (int)getPos;

- (MMCKnob_LocationEnum *)getKnobLoc;

@end

__attribute__((always_inline)) inline void MMCMove_init() {}

#define ComMahfouzMulticCoreMove MMCMove

@interface MMCMove_Immutable : NSObject < MMCMove > {
 @public
  int knobPos_;
  MMCKnob_LocationEnum *knobLocation_;
}

- (id)initWithInt:(int)pos
withMMCKnob_LocationEnum:(MMCKnob_LocationEnum *)knobLocation;

- (int)getPos;

- (MMCKnob_LocationEnum *)getKnobLoc;

- (NSString *)description;

- (void)copyAllFieldsTo:(MMCMove_Immutable *)other;

@end

__attribute__((always_inline)) inline void MMCMove_Immutable_init() {}

J2OBJC_FIELD_SETTER(MMCMove_Immutable, knobLocation_, MMCKnob_LocationEnum *)

@interface MMCMove_Mutable : NSObject < MMCMove > {
 @public
  int pos_;
  MMCKnob_LocationEnum *knobLocation_;
}

- (int)getPos;

- (MMCKnob_LocationEnum *)getKnobLoc;

- (void)setWithMMCKnob_LocationEnum:(MMCKnob_LocationEnum *)loc
                            withInt:(int)newPos;

- (MMCMove_Immutable *)toImmutable;

- (void)copyIntoWithMMCMove_Mutable:(MMCMove_Mutable *)other OBJC_METHOD_FAMILY_NONE;

- (NSString *)description;

- (id)init;

- (void)copyAllFieldsTo:(MMCMove_Mutable *)other;

@end

__attribute__((always_inline)) inline void MMCMove_Mutable_init() {}

J2OBJC_FIELD_SETTER(MMCMove_Mutable, knobLocation_, MMCKnob_LocationEnum *)

#endif // MMCMove_H
