//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: MulticRandomAlgo.java
//
//  Created by amahfouz on 6/4/14.
//

#include "Move.h"
#include "MoveIterator.h"
#include "MutableGameState.h"
#include "java/lang/Math.h"
#include "java/util/ArrayList.h"
#include "java/util/List.h"

#import "MulticRandomAlgo.h"

@implementation MMCMulticRandomAlgo

- (id<MMCMove>)findNextMoveWithMMCMutableGameState:(MMCMutableGameState *)gameState {
  MMCMoveIterator *iter = [[MMCMoveIterator alloc] initWithMMCMutableGameState:gameState];
  if (![iter hasNext]) return nil;
  id<JavaUtilList> validMoves = [[JavaUtilArrayList alloc] init];
  MMCMove_Mutable *mutableMove = [[MMCMove_Mutable alloc] init];
  while ([iter hasNext]) {
    [iter getNextWithMMCMove_Mutable:mutableMove];
    [validMoves addWithId:[mutableMove toImmutable]];
  }
  int randIndex = (int) [JavaLangMath floorWithDouble:[JavaLangMath random] * [validMoves size]];
  return [validMoves getWithInt:randIndex];
}

- (id)init {
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "findNextMoveWithMMCMutableGameState:", "findNextMove", "Lcom.mahfouz.multic.core.Move;", 0x1, NULL },
    { "init", NULL, NULL, 0x1, NULL },
  };
  static J2ObjcClassInfo _MMCMulticRandomAlgo = { "MulticRandomAlgo", "com.mahfouz.multic.core", NULL, 0x11, 2, methods, 0, NULL, 0, NULL};
  return &_MMCMulticRandomAlgo;
}

@end
