//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./util/MulticLog.java
//
//  Created by amahfouz on 6/4/14.
//

#import "MulticLog.h"

@interface MMUMulticLog : NSObject
@end

@implementation MMUMulticLog

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "debugWithNSString:", "debug", "V", 0x401, NULL },
    { "infoWithNSString:", "info", "V", 0x401, NULL },
    { "warnWithNSString:", "warn", "V", 0x401, NULL },
  };
  static J2ObjcClassInfo _MMUMulticLog = { "MulticLog", "com.mahfouz.multic.util", NULL, 0x201, 3, methods, 0, NULL, 0, NULL};
  return &_MMUMulticLog;
}

@end
