//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: MulticMoveAlgo.java
//
//  Created by amahfouz on 6/4/14.
//

#ifndef _MMC_MulticMoveAlgo_H_
#define _MMC_MulticMoveAlgo_H_

@class MMCDifficultyEnum;
@class MMCMutableGameState;
@protocol MMCMove;

#import "JreEmulation.h"


/**
 @brief Algorithm to pick the computer move given a position.
 */
@protocol MMCMulticMoveAlgo < NSObject, JavaObject >

/**
 @brief Find the next move given the current game state.
 */

- (id<MMCMove>)findNextMoveWithMMCMutableGameState:(MMCMutableGameState *)curGameState;

@end

__attribute__((always_inline)) inline void MMCMulticMoveAlgo_init() {}

#define ComMahfouzMulticCoreMulticMoveAlgo MMCMulticMoveAlgo


/**
 @brief Factory to create an algorithm for the specified difficulty level.
 */
@protocol MMCMulticMoveAlgo_Factory < NSObject, JavaObject >

- (id<MMCMulticMoveAlgo>)createWithMMCDifficultyEnum:(MMCDifficultyEnum *)difficulty;

@end

__attribute__((always_inline)) inline void MMCMulticMoveAlgo_Factory_init() {}

#endif // _MMC_MulticMoveAlgo_H_
