//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: MulticGameCell.java
//
//  Created by amahfouz on 6/4/14.
//

#include "Player.h"

#import "MulticGameCell.h"

@implementation MMCMulticGameCell

- (id)initWithInt:(int)cellIndex
withMMCPlayerEnum:(MMCPlayerEnum *)occupantIfAny {
  if (self = [super init]) {
    self->cellIndex_ = cellIndex;
    self->occupantIfAny_ = occupantIfAny;
  }
  return self;
}

- (int)getCellIndex {
  return self->cellIndex_;
}

- (MMCPlayerEnum *)getOccupantIfAny {
  return self->occupantIfAny_;
}

- (BOOL)isEmpty {
  return occupantIfAny_ == nil;
}

- (void)copyAllFieldsTo:(MMCMulticGameCell *)other {
  [super copyAllFieldsTo:other];
  other->cellIndex_ = cellIndex_;
  other->occupantIfAny_ = occupantIfAny_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "initWithInt:withMMCPlayerEnum:", "MulticGameCell", NULL, 0x1, NULL },
    { "getCellIndex", NULL, "I", 0x1, NULL },
    { "getOccupantIfAny", NULL, "Lcom.mahfouz.multic.core.Player;", 0x1, NULL },
    { "isEmpty", NULL, "Z", 0x1, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "cellIndex_", NULL, 0x12, "I", NULL,  },
    { "occupantIfAny_", NULL, 0x12, "Lcom.mahfouz.multic.core.Player;", NULL,  },
  };
  static J2ObjcClassInfo _MMCMulticGameCell = { "MulticGameCell", "com.mahfouz.multic.core", NULL, 0x11, 4, methods, 2, fields, 0, NULL};
  return &_MMCMulticGameCell;
}

@end
