//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: MulticException.java
//
//  Created by amahfouz on 6/4/14.
//

#ifndef _MMC_MulticException_H_
#define _MMC_MulticException_H_

@class MMCMulticGameCell;

#import "JreEmulation.h"
#include "java/lang/Exception.h"


/**
 @brief Exception indicating invalid game move or state.
 */
@interface MMCMulticException : JavaLangException {
 @public
  MMCMulticGameCell *cellIfAny_;
}

- (id)initWithNSString:(NSString *)detailMessage
 withMMCMulticGameCell:(MMCMulticGameCell *)gameCell;

- (MMCMulticGameCell *)getCellIfAny;

- (void)copyAllFieldsTo:(MMCMulticException *)other;

@end

__attribute__((always_inline)) inline void MMCMulticException_init() {}

J2OBJC_FIELD_SETTER(MMCMulticException, cellIfAny_, MMCMulticGameCell *)

typedef MMCMulticException ComMahfouzMulticCoreMulticException;

#endif // _MMC_MulticException_H_
