//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: MulticMoveAlgo.java
//
//  Created by amahfouz on 6/4/14.
//

#include "Difficulty.h"
#include "Move.h"
#include "MutableGameState.h"

#import "MulticMoveAlgo.h"

@interface MMCMulticMoveAlgo : NSObject
@end

@implementation MMCMulticMoveAlgo

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "findNextMoveWithMMCMutableGameState:", "findNextMove", "Lcom.mahfouz.multic.core.Move;", 0x401, NULL },
  };
  static J2ObjcClassInfo _MMCMulticMoveAlgo = { "MulticMoveAlgo", "com.mahfouz.multic.core", NULL, 0x201, 1, methods, 0, NULL, 0, NULL};
  return &_MMCMulticMoveAlgo;
}

@end

@interface MMCMulticMoveAlgo_Factory : NSObject
@end

@implementation MMCMulticMoveAlgo_Factory

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "createWithMMCDifficultyEnum:", "create", "Lcom.mahfouz.multic.core.MulticMoveAlgo;", 0x401, NULL },
  };
  static J2ObjcClassInfo _MMCMulticMoveAlgo_Factory = { "Factory", "com.mahfouz.multic.core", "MulticMoveAlgo", 0x209, 1, methods, 0, NULL, 0, NULL};
  return &_MMCMulticMoveAlgo_Factory;
}

@end
