//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./util/MulticLog.java
//
//  Created by amahfouz on 6/4/14.
//

#ifndef _MMU_MulticLog_H_
#define _MMU_MulticLog_H_

#import "JreEmulation.h"


/**
 @brief Logging facility.
 */
@protocol MMUMulticLog < NSObject, JavaObject >

- (void)debugWithNSString:(NSString *)message;

- (void)infoWithNSString:(NSString *)message;

- (void)warnWithNSString:(NSString *)message;

@end

__attribute__((always_inline)) inline void MMUMulticLog_init() {}

#define ComMahfouzMulticUtilMulticLog MMUMulticLog

#endif // _MMU_MulticLog_H_
