//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: XGameGridUiModel.java
//
//  Created by amahfouz on 6/4/14.
//

#ifndef _MMU_XGameGridUiModel_H_
#define _MMU_XGameGridUiModel_H_

@class MMCPlayerEnum;

#import "JreEmulation.h"


/**
 @brief UI model for the game grid specifying cell content and color.
 */
@protocol MMUXGameGridUiModel < NSObject, JavaObject >

- (int)getNumCells;

- (NSString *)getCellContentWithInt:(int)index;

- (MMCPlayerEnum *)getCellOccupantIfAnyWithInt:(int)index;

@end

__attribute__((always_inline)) inline void MMUXGameGridUiModel_init() {}

#define ComMahfouzMulticUimXGameGridUiModel MMUXGameGridUiModel

@protocol MMUXGameGridUiModel_Provider < NSObject, JavaObject >

- (id<MMUXGameGridUiModel>)get;

@end

__attribute__((always_inline)) inline void MMUXGameGridUiModel_Provider_init() {}

@interface MMUXGameGridUiModel_Util : NSObject {
}

+ (BOOL)isEmptyWithMMUXGameGridUiModel:(id<MMUXGameGridUiModel>)grid;

- (id)init;

@end

__attribute__((always_inline)) inline void MMUXGameGridUiModel_Util_init() {}

#endif // _MMU_XGameGridUiModel_H_
