//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: XGameGridUiModel.java
//
//  Created by amahfouz on 6/4/14.
//

#include "Player.h"

#import "XGameGridUiModel.h"

@interface MMUXGameGridUiModel : NSObject
@end

@implementation MMUXGameGridUiModel

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "getNumCells", NULL, "I", 0x401, NULL },
    { "getCellContentWithInt:", "getCellContent", "Ljava.lang.String;", 0x401, NULL },
    { "getCellOccupantIfAnyWithInt:", "getCellOccupantIfAny", "Lcom.mahfouz.multic.core.Player;", 0x401, NULL },
  };
  static J2ObjcClassInfo _MMUXGameGridUiModel = { "XGameGridUiModel", "com.mahfouz.multic.uim", NULL, 0x201, 3, methods, 0, NULL, 0, NULL};
  return &_MMUXGameGridUiModel;
}

@end

@interface MMUXGameGridUiModel_Provider : NSObject
@end

@implementation MMUXGameGridUiModel_Provider

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "get", NULL, "Lcom.mahfouz.multic.uim.XGameGridUiModel;", 0x401, NULL },
  };
  static J2ObjcClassInfo _MMUXGameGridUiModel_Provider = { "Provider", "com.mahfouz.multic.uim", "XGameGridUiModel", 0x209, 1, methods, 0, NULL, 0, NULL};
  return &_MMUXGameGridUiModel_Provider;
}

@end

@implementation MMUXGameGridUiModel_Util

+ (BOOL)isEmptyWithMMUXGameGridUiModel:(id<MMUXGameGridUiModel>)grid {
  int numCells = [((id<MMUXGameGridUiModel>) nil_chk(grid)) getNumCells];
  for (int i = 0; i < numCells; i++) {
    if ([grid getCellOccupantIfAnyWithInt:i] != nil) return NO;
  }
  return YES;
}

- (id)init {
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "isEmptyWithMMUXGameGridUiModel:", "isEmpty", "Z", 0x9, NULL },
    { "init", NULL, NULL, 0x1, NULL },
  };
  static J2ObjcClassInfo _MMUXGameGridUiModel_Util = { "Util", "com.mahfouz.multic.uim", "XGameGridUiModel", 0x19, 2, methods, 0, NULL, 0, NULL};
  return &_MMUXGameGridUiModel_Util;
}

@end
